name: Setup Exoscale
author: nhedger
description: Setup Exoscale CLI in GitHub Actions
branding:
  color: white
  icon: terminal
inputs:
  token:
    description: GitHub Actions token to authenticate API requests
    required: true
    default: ${{ github.token }}
  version:
    description: The version of the Exoscale CLI to install
    required: true
    default: latest
  account:
    description: The Exoscale account name
    required: false
  zone:
    description: The Exoscale default zone
    required: true
    default: ch-gva-2
  endpoint:
    description: The Exoscale API endpoint (defaults to https://api-{zone}.exoscale.com/v2)
    required: false
  key:
    description: The Exoscale API key
    required: false
  secret:
    description: The Exoscale API secret
    required: false
runs:
  using: "node20"
  main: "dist/index.mjs"
