name: Test

on:
  push:
    branches: [ main, "releases/v*"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest ]
        version: [ "latest", "1.95.0" ]
        include:
          - os: windows-11-arm
            version: "1.76.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Exoscale CLI
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Test the CLI
        run: exo version
  test-authenticated:
    name: Test Authenticated
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest ]
        version: [ "latest", "1.95.0" ]
        include:
          - os: windows-11-arm
            version: "1.76.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Exoscale CLI
        uses: ./
        with:
          zone: ch-gva-2
          version: ${{ matrix.version }}
          account: ${{ secrets.EXOSCALE_ACCOUNT }}
          key: ${{ secrets.EXOSCALE_KEY }}
          secret: ${{ secrets.EXOSCALE_SECRET }}
      - name: Test the CLI
        run: exo config list
